server:
  port: 8100
spring:
  # 应用名称（nacos会将该名称当做服务名称）
  application:
    name: oneflow-prm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/local?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123
  # 关闭nacos
  cloud:
    nacos:
      config:
        enabled: false
        refresh-enabled: false
      discovery:
        enabled: false
        instance-enabled: false

# mybatis-plus其他配置可见：https://www.jianshu.com/p/e303da331bf0
mybatis-plus:
  # mybatis默认的mapper.xml路径地址是classpath*:/mapper/**/*.xml，如果不是需要通过以下配置设置
  mapper-locations: classpath:/mapper/*.xml
  # MyBatis 别名包扫描路径，通过该属性可以给包中的类注册别名，多个路径用逗号分割
  type-aliases-package: com.oneflow.prm.entity.dao
  configuration:
    # mybatis-plus的驼峰映射，默认为true是打开的。false关闭后，可以使用@TableField做映射
    map-underscore-to-camel-case: false
    # 将sql打印在控制台上
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 将sql打印在日志文件中
#    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
