apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecoflow-prm
  namespace: it-project
  labels:
    app: ecoflow-prm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecoflow-prm
  template:
    metadata:
      labels:
        app: ecoflow-prm
    spec:
      containers:
        - name: ecoflow-prm
          image: harbor.ecoflow.com/it/ecoflow-prm:master
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "java", "-XX:+HeapDumpOnOutOfMemoryError", "-XX:HeapDumpPath=/logs/prm_heapDump.hprof", "-jar", "app.jar" ]
          args:
            - '--spring.profiles.active=prd'
            - '--spring.cloud.nacos.config.namespace=ecoflow-k8s'
            - '--spring.cloud.nacos.config.server-addr=nacos-headless'
            - '--spring.cloud.nacos.discovery.namespace=ecoflow-k8s'
            - '--spring.cloud.nacos.discovery.server-addr=nacos-headless'
          ports:
            - containerPort: 8100
          volumeMounts:
            - mountPath: /logs
              name: log-volume
          resources:
            limits:
              cpu: "4"
              memory: 4096Mi
            requests:
              cpu: "4"
              memory: 4096Mi
          readinessProbe:
            httpGet:
              path: /ecoflow/prm/actuator/health
              port: 8100
            initialDelaySeconds: 30
      volumes:
        - name: log-volume
          hostPath:
            path: /data
            type: Directory
---

apiVersion: v1
kind: Service
metadata:
  name: ecoflow-prm
  namespace: it-project
  labels:
    app: ecoflow-prm
spec:
  selector:
    app: ecoflow-prm
  ports:
    - port: 8100
      targetPort: 8100

