### 登录获取code
POST https://sit-it-auth.oneflow.com/oneflow/auth/sms/login
Content-Type: application/json

{
  "mobile": {{admin}},
  "code": "1234",
  "redirect_url": "https://sit-oms.oneflow.com/login",
  "client_id": "prm"
}

> {% client.global.set("request_code", response.body.data.code); %}

### 根据code获取token
GET https://sit-it-auth.oneflow.com/api/sso/auth?code={{request_code}}&redirect_url=https://sit-oms.oneflow.com/login
Accept: */*

> {% client.global.set("token", "Bearer " + response.body.token); %}


